# Generated by Django 4.2.16 on 2024-09-20 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('access', 'Access'), ('location', 'Location'), ('occupancy', 'Occupancy'), ('electricity', 'Electricity'), ('ignition', 'Ignition'), ('passenger_count', 'Passenger Count')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asset')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='vehiclehistory',
            name='vehicle_id',
        ),
        migrations.DeleteModel(
            name='HotelRoomHistory',
        ),
        migrations.DeleteModel(
            name='VehicleHistory',
        ),
    ]
