# Generated by Django 4.2.16 on 2024-09-26 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assetevent_remove_vehiclehistory_vehicle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_asset_id', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=10)),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('transfer', 'Transfer'), ('mobile_money', 'Mobile_money')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_ref', models.CharField(max_length=255, unique=True)),
                ('processor_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_outgoing', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.asset')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_ref'], name='core_transa_transac_22fca0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_status'], name='core_transa_payment_67d780_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp'], name='core_transa_timesta_a5c12f_idx'),
        ),
    ]
