# Generated by Django 4.2.16 on 2024-09-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assetevent_remove_vehiclehistory_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
