# Generated by Django 4.2.16 on 2024-09-25 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assetevent_remove_vehiclehistory_vehicle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_passengers', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_data', models.JSONField()),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
