# Generated by Django 4.2.16 on 2024-09-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehiclehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleHistory',
        ),
    ]
