# Generated by Django 4.2.16 on 2024-09-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_account_number_alter_user_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelroom',
            unique_together={('hotel', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('fleet', 'vehicle_number')},
        ),
    ]
