# Generated by Django 4.2.16 on 2024-09-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_remove_role_role_role_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='admin', max_length=20),
            preserve_default=False,
        )
    ]
