# Generated by Django 4.2.16 on 2024-09-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_delete_payment_and_more'),
        ('core', '0006_transaction_role_role_delete_payment_and_more'),
    ]

    operations = [
    ]
