# Generated by Django 4.2.16 on 2024-09-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20240930_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='asset_id',
            new_name='asset',
        ),
    ]
