# Generated by Django 4.2.16 on 2024-09-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20240930_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='activation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='expiry_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='activation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='expiry_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetevent',
            name='event_type',
            field=models.CharField(choices=[('access', 'Access'), ('location', 'Location'), ('occupancy', 'Occupancy'), ('electricity', 'Electricity'), ('ignition', 'Ignition'), ('passenger_count', 'Passenger Count'), ('active', 'Active'), ('inactive', 'Inactive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
