# Generated by Django 4.2.16 on 2024-10-02 20:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hotelroom_activation_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_distance',
            field=models.FloatField(default=0.0),
        ),
    ]
