# Generated by Django 4.2.16 on 2024-10-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_asset_id_transaction_asset'),
        ('core', '0009_transaction_role_created_at_vehicle_last_latitude_and_more'),
    ]

    operations = [
    ]
