# Generated by Django 4.2.16 on 2024-10-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_vehiclehistory'),
        ('core', '0010_merge_20241003_0307'),
    ]

    operations = [
    ]
