# Generated by Django 4.2.16 on 2024-10-09 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20241009_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='activation_timestamp',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='expiry_timestamp',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='activation_timestamp',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='expiry_timestamp',
        ),
        migrations.AlterField(
            model_name='assetevent',
            name='event_type',
            field=models.CharField(choices=[('access', 'Access'), ('location', 'Location'), ('occupancy', 'Occupancy'), ('electricity', 'Electricity'), ('ignition', 'Ignition'), ('passenger_count', 'Passenger Count')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_latitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
