# Generated by Django 4.2.16 on 2024-10-10 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_asset_asset_number_alter_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(limit_choices_to={'asset_type': 'hotel'}, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.asset', to_field='asset_number'),
        ),
        migrations.AlterField(
            model_name='role',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.asset', to_field='asset_number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fleet',
            field=models.ForeignKey(limit_choices_to={'asset_type': 'vehicle'}, on_delete=django.db.models.deletion.CASCADE, related_name='fleet', to='core.asset', to_field='asset_number'),
        ),
    ]
