# Generated by Django 4.2.16 on 2024-10-10 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_asset_asset_number_alter_hotelroom_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.asset', to_field='asset_number'),
        ),
    ]
