# Generated by Django 4.2.16 on 2024-10-10 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_transaction_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetevent',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.asset', to_field='asset_number'),
        ),
    ]
