# Generated by Django 4.2.16 on 2024-10-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_assetevent_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
