# Generated by Django 4.2.16 on 2024-10-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_hotelroom_status_alter_vehicle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sub_asset_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sub_asset_number',
            field=models.CharField(default='002', max_length=10),
            preserve_default=False,
        ),
    ]
