# Generated by Django 4.2.16 on 2024-10-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_transaction_sub_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetevent',
            name='object_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=10),
        ),
    ]
