# Generated by Django 4.2.16 on 2024-10-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_hotelroom_activation_timestamp_and_more'),
        ('core', '0017_remove_transaction_sub_asset_id_and_more'),
    ]

    operations = [
    ]
